POST http://docker:8080/groups
Accept: application/json
Content-Type: application/json

{
  "name": "group of testers",
  "terminateTask": {
    "name": "dep-tester-2",
    "status": "STATE_1"
  },
  "tasks": [
    {
      "name": "dep-tester-1",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "privileged": true,
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31101}
         ],
        "volumes": [
          {"containerPath": "/mnt/anything", "hostPath": "/mnt/something/else"}
         ]
      }
    },
    {
      "name": "dep-tester-2",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31102}
         ]
      },
      "dependsOn": {
        "name": "dep-tester-1",
        "status": "UP"
      }
    },
    {
      "name": "dep-tester-3",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31103}
         ]
      },
      "dependsOn": {
        "name": "dep-tester-2",
        "status": "STATE_1"
      }
    },
    {
      "name": "dep-tester-4",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31104}
         ]
      },
      "dependsOn": {
        "name": "dep-tester-3",
        "status": "STATE_2"
      }
    },
    {
      "name": "dep-tester-5",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31105}
         ]
      },
      "dependsOn": {
        "name": "dep-tester-1",
        "status": "UP"
      }
    },
    {
      "name": "dep-tester-6",
      "cpus": 0.2,
      "mem": 64,
      "container": {
        "image": "vtajzich/yowie-demo:dependency-tester",
        "network": "BRIDGE",
        "portMappings": [
          {"containerPort": 8080, "hostPort": 31106}
         ]
      },
      "dependsOn": {
        "name": "dep-tester-3",
        "status": "UP"
      }
    }
  ]
}