POST http://docker:8080/groups
Accept: application/json
Content-Type: application/json

{
    "name": "apps",
    "tasks": [
        {
            "name": "movie-finder",
            "cpus": 1,
            "mem": 128,
            "container": {
                "image": "vtajzich/yowie-demo:movie-finder",
                "network": "BRIDGE",
                "portMappings": [
                    {
                        "containerPort": 8080,
                        "hostPort": 31100
                    }
                ]
            },
            "env": {
                "spring.datasource.url": "jdbc:mysql://docker/movie_app",
                "spring.datasource.username": "vitek",
                "spring.datasource.password": "Password1"
            }
        }
    ]
}
